version: '3.9'

services:
  deepstream:
    build: ./docker_image
    image: deepstream_app:experimental
    container_name: deepstream_app
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/deepstream_app
    working_dir: /deepstream_app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
    ports:
      - "8554:8554"  # Example RTSP
      - "5000:5000"  # Example HTTP inference API
      - "8888:8888"  # Example Jupyter or UI
